<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">

  <title><![CDATA[Category: Flake8 | Dark Matter in Cyberspace]]></title>
  <link href="http://leetschau.github.io/blog/categories/flake8/atom.xml" rel="self"/>
  <link href="http://leetschau.github.io/"/>
  <updated>2016-11-11T14:51:43+08:00</updated>
  <id>http://leetschau.github.io/</id>
  <author>
    <name><![CDATA[Li Chao]]></name>
    
  </author>
  <generator uri="http://octopress.org/">Octopress</generator>

  
  <entry>
    <title type="html"><![CDATA[使用flake8做Python Linter]]></title>
    <link href="http://leetschau.github.io/blog/2016/05/24/204911/"/>
    <updated>2016-05-24T20:49:11+08:00</updated>
    <id>http://leetschau.github.io/blog/2016/05/24/204911</id>
    <content type="html"><![CDATA[<p>今天写Python脚本时遇到一个问题，重构代码时，修改了一个变量名，
但只改了正常分支中的，忘了改错误处理分支中的，由于没有Linter做未定义变量检查，
bug在本机测试时并没有被发现，直到被push到remote repo，
在Jenkins job里运行几次出错后才被发现。
解决方案是安装flake8以及vim插件。</p>

<p>For Python 2.x: <code>pip install flake8</code>，
vim的syntastic插件不需要配置。</p>

<p>For Python 3.x，首先要安装flake8 for Python 3.x:</p>

<pre><code>sudo apt-get install python3-pip
sudo pip3 install flake8
</code></pre>

<p>命令行中检查文件命令：<code>python3 -m pyflakes syncRecurrences.py</code>.</p>

<p>配置vim语法检查的方法是在.vimrc文件里增加一下配置项：</p>

<pre><code>let g:syntastic_python_python_exec = '/usr/bin/python3'
let g:syntastic_python_flake8_exec = 'python3'
let g:syntastic_python_flake8_args = ['-m', 'flake8']
</code></pre>

<p>配置好后用vim打开python脚本，保存文件后，在未声明的变量行上会出现下面的错误信息：</p>

<pre><code>undefined name 'objId' [F821]
</code></pre>
]]></content>
  </entry>
  
</feed>
